version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: dailysql-postgres-experimental
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dailysql
    ports:
      - "5432:5432"
    volumes:
      - dailysql_pgdata:/var/lib/postgresql/data

  api:
    build: ./backend
    container_name: dailysql-api-experimental
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/dailysql
      REDIS_URL: redis://redis:6379
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres
      - redis
      - python-runner
      - pyspark-runner

  redis:
    image: redis:7
    container_name: dailysql-redis-experimental
    ports:
      - "6379:6379"

  python-runner:
    build:
      context: ./runners/python
    container_name: dailysql-python-runner-experimental
    image: dailysql-python-runner:latest
    ports:
      - "5001:5001"
    restart: always

  pyspark-runner:
    build:
      context: ./runners/pyspark
    container_name: dailysql-pyspark-runner-experimental
    image: dailysql-pyspark-runner:latest
    ports:
      - "5002:5002"
    restart: always

volumes:
  dailysql_pgdata:

